installedESLint: true
parser: babel-eslint
extends: airbnb
settings:
  import/resolver:
    webpack:
      config: 'webpack.config.js'
env:
  browser: true
plugins:
  - react
ecmaFeatures:
  classes: true
  jsx: true
rules:
  global-require: 0
  no-undef: 0
  max-len: 0
  react/prop-types: 1
  react/react-in-jsx-scope: 0
  react/jsx-filename-extension: 0
  no-underscore-dangle: ["error", { "allow": ["__REDUX_DEVTOOLS_EXTENSION__"] }]
