export const PUSH_BUTTON_IN_ELEVATOR = 'PUSH_BUTTON_IN_ELEVATOR';
export const CHANGE_ELEVATOR_DIRECTION = 'CHANGE_ELEVATOR_DIRECTION';
export const CHANGE_ELEVATOR_STATE = 'CHANGE_ELEVATOR_STATE';
export const CHANGE_ELEVATOR_LEVEL = 'CHANGE_ELEVATOR_LEVEL';
export const OPEN_ELEVATOR_DOORS = 'OPEN_ELEVATOR_DOORS';
export const CLOSE_ELEVATOR_DOORS = 'CLOSE_ELEVATOR_DOORS';
